name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: mod2mp4-rs-${{ matrix.os }}
          path: |
            target/release/mod2mp4-rs
            target/release/mod2mp4-rs.exe
